version: "3.9"

services:
  kascad-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN_GCP=${GITHUB_TOKEN_GCP}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
