version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN:-}
        - NODE_ENV=development
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - NODE_ENV=development
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
