name: Deploy API - Production

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PRODUCTION }}

      - name: Docker login to Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env

      - name: Debug .env content (first 10 lines)
        run: head -n 10 .env || echo "No env variables found"

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN_GCP }} \
            -t europe-west1-docker.pkg.dev/kascad-production/kascad/kascad-api:${{ github.sha }} \
            .
          docker push europe-west1-docker.pkg.dev/kascad-production/kascad/kascad-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: kascad-api
          region: europe-west1
          image: europe-west1-docker.pkg.dev/kascad-production/kascad/kascad-api:${{ github.sha }}
          timeout: 600s
          project_id: kascad-production

      - name: Clean up
        run: rm .env
